### ISSUE TITLE
Feature: 프론트와 백앤드 연결 : 게시글 

### ISSUE THREAD

**Issue by codekmj1** [HwangSeungHyeon/buysell-ui#2]
## Description
프론트와 백앤드 게시글 연결

## Todo
- [x] 상품등록 성공
- [x] 상품 조회 성공
- [x]  상품 수정 성공
- [x] 상품 삭제 성공
- [x] 댓글 조회 성공
- [x] 게시글 찜 성공

## ETC
위의 내용이 완료되어야 합니다.
