### ISSUE TITLE
Feature: 프론트와 백엔드 댓글 연결

### ISSUE THREAD

**Issue by codekmj1** [HwangSeungHyeon/buysell-ui#4]
## Description
프론트와 백엔드 댓글 

## Todo
- [x] 댓글 작성 성공
- [x] 댓글 수정 성공
- [x] 댓글 삭제 성공
- [x]  댓글 좋아요 성공
